### ISSUE TITLE
Intermittent entry point behavior when doing quick kills/steps and switching between optimizations enabled/disabled

### ISSUE THREAD

**Issue by zobermiller** [EpicGamesExt/raddebugger#284]
This is a bit of a weird thing I'm running into, and it seems to be intermittent as I haven't been able to consistently reproduce it, but if I start and stop debugging a process quite quickly and then recompile my program with optimizations enabled/disabled (i.e. the opposite of what it was before), a subsequent run will sometimes result in the entry point being set to a different spot in the code. Oddly enough, this new entry point seems to be consistent (in this case at `CreateWindowEx`).

Again, hard to explain, so here's a little video with what I mean:

https://github.com/EpicGamesExt/raddebugger/assets/4643387/5ee5110e-dbaa-4511-aff6-3f87f4cba195

In the video, I do the following:
* Compile my program initially with optimizations disabled (`/Od`).
* Start stepping through the program in raddbg and either hitting F10 fast or by hitting F5.
* Kill my program in raddbg with Shift + F5.
* Repeat the above 2 steps a few times.
* Recompile my program with optimizations enabled (`/O2`).
* Navigate back to raddbg and hit F10.

You'll see it starts me in a different area of code compared to my `int main()` entry point. If I quit out of raddbg and re-open it, it will start me off at the correct entry point. So this doesn't seem related to anything in the `.rdi` file, instead seeming to be an issue within the particular raddbg session itself. You can see at the very end I close out of raddbg, re-open it, and hit F10 to show where the entry point _should_ be with optimizations enabled.

I should also mention if I do a similar workflow in my program with optimizations enabled *first*, then re-compile with optimizations disabled, I can see similar behavior, so it's not just disabled -> enabled; it can be the vice versa as well.

Lastly, I should note it's quite variable with regards to how often I see this issue. When recording the video for demonstration, there were times I needed 5 or more tries to get it to happen. Other times, I could get it to happen every time I tried. But overall I don't exactly know how to get this to happen consistently or exactly what the cause seems to be.

Sorry if this isn't enough information. I can try to provide more if you need.

**Comment by ryanfleury** [comment]
Are you able to try reproducing this issue again with the top of the `master` branch? It is possible that it has been resolved, since many of the core layers which may have been causing this problem have been passed over. Thanks.

**Comment by zobermiller** [comment]
Really sorry for the delay. I just tried reproducing this around 10 times and was not able to. Due to the intermittent nature, it's always possible the issue is still there, but I feel I would have run into it by now.

So I think we can close this as resolved. Thanks a lot!
