### ISSUE TITLE
[Bug] Crash with di_search_thread.

### ISSUE THREAD

**Issue by mistymntncop** [EpicGamesExt/raddebugger#363]
```
[Window Title]
Fatal Exception

[Content]
A fatal exception (code 0xc0000005) occurred. The process is terminating.

Press Ctrl+C to copy this text to clipboard, then create a new issue at
https://github.com/EpicGamesExt/raddebugger/issues

Call stack:
1. [0x7ff62a9e6200] arena_push +32, base_arena.c line 85
2. [0x7ff62aa4d37b] di_search_thread__entry_point +2059, dbgi.c line 1427
3. [0x7ff62aa009ba] os_w32_thread_entry_point +90, os_core_win32.c line 151
4. [0x7ffc0dc07374] KERNEL32
5. [0x7ffc0ea5cc91] ntdll

Version: 0.9.14 [b99e1022]

[Close]

```
I am encountering this bug sometimes when I enter variables in the watch window. I don't know if this matters but I am doing multi-process debugging. It seems for some reason the [key is not being found](https://github.com/EpicGamesExt/raddebugger/blob/b99e10224f7e85edb148f789eb4b95709b986d80/src/dbgi/dbgi.c#L1361). Still trying to get more information.

**Comment by foxblock** [comment]
I am having a similar issue, which might be related:
```
[Window Title]
Fatal Exception

[Content]
A fatal exception (code 0xc0000005) occurred. The process is terminating.

Press Ctrl+C to copy this text to clipboard, then create a new issue at
https://github.com/EpicGamesExt/raddebugger/issues

Call stack:
1. [0x7ff7be7b653e] arena_release +14, base_arena.c line 73
2. [0x7ff7be81e1c3] di_search_evictor_thread__entry_point +883, dbgi.c line 1530
3. [0x7ff7be7d0e9a] os_w32_thread_entry_point +90, os_core_win32.c line 151
4. [0x7ffd6447259d] KERNEL32
5. [0x7ffd6624af38] ntdll

Version: 0.9.14 [b99e1022]

[Schließen]
```

I can reliably cause this crash to happen by just starting the application and switching between tabs in one of the panels. After 2-4 tab switches the crash occurs.
It only happens on 0.9.14, 0.9.13 (f792da5d) is working fine.
If it helps, I can try to narrow it down with a git bisect - just ask for it.

OS is Windows 11 Pro 23H2 (build 22631.4460)

**Comment by ryanfleury** [comment]
Sorry about that. Looks like I screwed up the synchronization of the new search stuff, and didn't see it happen on my development workstation. I'll thoroughly investigate this and fix it ASAP.

**Comment by ryanfleury** [comment]
Okay, I ended up reproducing at least one of the bugs here (the crash in `arena_push`), and I believe I have solved the root cause of at least one of them, and I have written a plausible fix for the other one (the crash in `arena_clear`). Would you both mind giving the top of `dev` or `master` a try and letting me know if you still see the issue?

**Comment by mistymntncop** [comment]
I tried it and am no longer experiencing the crash :)

**Comment by ryanfleury** [comment]
Sounds good - I believe I've fixed the other one too, so I will close this, but just let me know if you hit the issue again @foxblock and I'll reopen & investigate further.

**Comment by foxblock** [comment]
Unfortunately I am still getting the error with the same steps to reproduce:
```
[Window Title]
Fatal Exception

[Content]
A fatal exception (code 0xc0000005) occurred. The process is terminating.

Press Ctrl+C to copy this text to clipboard, then create a new issue at
https://github.com/EpicGamesExt/raddebugger/issues

Call stack:
1. [0x7ff78d34653e] arena_release +14, base_arena.c line 73
2. [0x7ff78d3ae3b3] di_search_evictor_thread__entry_point +883, dbgi.c line 1539
3. [0x7ff78d36103a] os_w32_thread_entry_point +90, os_core_win32.c line 151
4. [0x7ffd6447259d] KERNEL32
5. [0x7ffd6624af38] ntdll

Version: 0.9.14 [9eb482b1]

[Schließen]
```

**Comment by ryanfleury** [comment]
Can you pull and try again @foxblock? I have pushed another plausible fix.

**Comment by foxblock** [comment]
Hi @ryanfleury,
that latest commit seems to have done the trick. At least I could not reproduce the error anymore.
Thanks for the quick fix!

**Comment by ryanfleury** [comment]
Sounds good, closing this now!
