### ISSUE TITLE
Working Directory Target option sometimes gets erased after re-launching raddbg

### ISSUE THREAD

**Issue by jakubtomsu** [EpicGamesExt/raddebugger#555]
I have a regular target set up in raddbg for launching my game, but it recently started erasing my working directory option after re-launch. This is annoying because it looks like the game crashed so it took a while to figure out the first time haha.

I have no idea why this is happening and can't see any pattern, it just sometimes slightly corrupts the config. But also I think if the executable is specified as full path raddbg should use the base path as the working directory.

I'm on the `0.9.20 ALPHA` release.

**Comment by ryanfleury** [comment]
This may have been caused by something I just fixed in 45d1f8e58b9fff15af4587ef802691d3802bec03. Would you mind giving it another try?

**Comment by jakubtomsu** [comment]
I just tried it with a build of the latest commit. The issue is still partially there, but I accidentally stumbled upon a fix on my side.

this was my *old* target config which is still broken:
```
target:
{
  enabled: 1
  executable: "buildsys.exe"
  label: hot
  arguments: "hotreload-run"
  debug_subprocesses: 1
  working_directory: ""
}
```

Which in raddbg shows up as this:

<img width="486" height="165" alt="Image" src="https://github.com/user-attachments/assets/023989e0-c63d-4105-a23b-0e0a560bf6c7" />

Now, if I set the working directory to `D:/projects/blockfps/` and close raddbg, the config field is still `working_directory: ""`.

However if I directly set the working directory in the config file to `../blockfps` (which is the root path of my project relative to raddbg install directory), and launch raddbg again, it magically works.

So the issue is fixed *for me* at the moment, however there is still something weird going on. So I suppose I can leave this issue open.

**Comment by yyamdev** [comment]
I am also running into this on 6543dad.

From my perspective the issue looks like this: In the debugger UI I set the working directory to be a different directory to the target executable, I use an absolute path. Then when I start debugging everything is fine. However when I save the project file, restart the debugger, open the project file again, the working directory field is empty in the UI so I have to set it again. The project file on disk has an empty string for "working_directory".

I have not read the code but I think this might be happening because the debugger interprets an empty working directory path to mean the same directory as the target executable? But I think it may also try to convert absolute paths into paths relative to the project file when it saves. In my case I set the working directory to the same directory that the project file is in, this would result in an empty path.

**Comment by SanielX** [comment]
I'm having a similar issue, probably not worth opening another issue for this.
If a project file is in exact same folder as the working directory, it'll save as empty string. I guess this is interpreted as "no value" by the debugger.
I believe it could be solved if relative paths started with `./`

**Comment by fartsicle** [comment]
I believe I just hit this as well. I'm on `v0.9.28-alpha`.

 My project is `Z:/radproj.rdbg`; setting the working directory to `Z:/` works for that session, but autosave/close rewrites it to `working_directory: ""` (so even editing the project file directly will eventually have it rewritten).

It seems to happen when the working directory is exactly the project file’s directory, so the relative path collapses to empty. `Z:` is a subst drive here, but that doesn’t seem essential to the bug.

My presumption, though I may be wrong, is that the empty working directory has it fall back to the debugger's working directory for the program you end up running, and that'll almost definitely be different (e.g. my RADD is at `C:\Tools\RADDebugger`) than what you would've intended.

Unfortunately for my specific case, `./` doesn't perfectly solve it because of what looks to be a separate bug related to root drives + working directory state. Although I can't find any issue or PR for it, I'll mention it here with what an AI I had investigate told me that sounds plausible, as AI do: 
> `./` gets resolved against the project directory, but RADD normalizes `Z:/./` to bare `Z:` instead of `Z:/`.

And so based off this information, I see that my program I run uses CreateProcess in it at some point in a way which to my understanding would depend on that passed in working directory state, and then the CreateProcess in my program will error and say it can't find the path I requested. And so essentially, RADD seems to launch my program properly with some sort of absolute path, but hand it this bad working directory state (if the AI is to be trusted) which shows up in this kind of program/case like mine.

I did some probes on the cwd via my program just so I could trust the AI's read on it a bit more, and this "bad working directory state" my program gets doesn't quite end up being `Z:` but it appears to be RADD's own working directory, so maybe something extra goes on there, but it does make me believe my presumption earlier for the other bug more. I tested it for that original case (`Z:/`) and my GetCurrentDirectoryA probe in that case also returned RADD's cwd (`C:\Tools\RADDebugger`).

At the bare minimum what's true is that my specific program breaks with `./` but not with `Z:/` as the set working directory when launching it from RADD, but `Z:/` incurs the "empty" saving problem I mentioned earlier so it's more hassle for me to use between sessions.

Hope this helps get the issue down. Thanks.
--Fart
