### ISSUE TITLE
Casting types to signed/unsigned in the watch window is broken

### ISSUE THREAD

**Issue by felpafel** [EpicGamesExt/raddebugger#562]
Casting an `uint32_t` that has the 31st bit set, to `int32_t` does nothing, and casting an `int32_t` to `uint32_t` returns a wrong value.

![raddbg](https://github.com/user-attachments/assets/ec42e1df-fe4e-4219-ad1e-00aba0869941)
![remedybg](https://github.com/user-attachments/assets/aa90c0df-9d80-4c69-a282-47440b8a51ac)

**Comment by ryanfleury** [comment]
Fixed in 87fa6b9239429828b6bc7fa069fec0471f48e7fe.

**Comment by felpafel** [comment]
Hello Ryan, thanks for your awesome work.

I don't know if I should comment on this issue or create a new one, but expressions with casting are still broken.

The expression in the following screenshot should return `false` instead of `true`.

![raddbg](https://github.com/user-attachments/assets/1b02f2eb-1e38-46c6-a65f-fcd45e8c9243)

**Comment by ryanfleury** [comment]
Ah, my mistake, I think this bug goes deeper - fixing it now...

**Comment by ryanfleury** [comment]
Okay, I think this should be fixed as of cd64d959ef6f552bb933fe2e6581b536efd35b8f. Let me know if you see any more issues.
