### ISSUE TITLE
The 'list' type view doesn't always work and crashes in some cases

### ISSUE THREAD

**Issue by Strewya** [EpicGamesExt/raddebugger#666]
Along with the crash (dump and stack below the image), from some other testing, it doesn't seem like the list view works if the member that is the next link isn't the first member of the struct, i.e. for a struct like
```cpp
struct chunk
{
    chunk *NextHashmap;
    chunk *NextPending;
// some more data here
};
```
using `list(Chunk, NextHashmap)` works as expected, but `list(Chunk, NextPending)` shows it as having a single element even tho there are many elements. I've added a screenshot to show the issue.

<img width="501" height="200" alt="Image" src="https://github.com/user-attachments/assets/959d7549-b158-4bfa-8737-767f577e92af" />

here is the expanded [0] element from the second expression:

<img width="511" height="364" alt="Image" src="https://github.com/user-attachments/assets/a23d357a-206b-48ba-a1cc-9f0353ce597c" />

As for the crash, it occured when using `list(Thing, NextChunk)`, where Thing is a
```cpp
  struct thing
  {
    u64 Flags;
    string DebugName;
    thing_handle Handle;

    thing *NextChunk;
    thing *PrevChunk;
    thing *NextMover;
    thing *PrevMover;
    thing *NextRetire;
    thing *NextType;
    thing *PrevType;
// a ton more data below
};
```

[Content]
A fatal exception (code 0xc0000005) occurred. The process is terminating.

Call stack:
1. [0x7ff7a44666bd] arena_pop_to +61, base_arena.c line 204
2. [0x7ff7a446687f] temp_end +31, base_arena.c line 262
3. [0x7ff7a47642fa] e_list_gather_artifact_create +1994, eval_types.c line 2704
4. [0x7ff7a4486802] ac_async_tick +4818, artifact_cache.c line 471
5. [0x7ff7a4475b92] async_thread_entry_point +338, base_entry_point.c line 206
6. [0x7ff7a44759db] supplement_thread_base_entry_point +43, base_entry_point.c line 152
7. [0x7ff7a448145e] os_w32_thread_entry_point +62, os_core_win32.c line 150
8. [0x7ffa98497374] KERNEL32
9. [0x7ffa99b5cc91] ntdll

Version: 0.9.23 [f5b94436]

[raddbg_crash_dump.dmp](https://github.com/user-attachments/files/23098666/raddbg_crash_dump.dmp)

**Comment by ryanfleury** [comment]
Can you try this on the top of `master`? I've fixed a few things with `list` since 0.9.23.

**Comment by Strewya** [comment]
All the same things happen on top of master, yeah.

**Comment by ryanfleury** [comment]
Got it, sorry about that, will look into this shortly.

**Comment by ryanfleury** [comment]
This should be fixed as of 766d717, but let me know if you run into any other issues.

**Comment by Strewya** [comment]
Okay, the crash no longer occurs, so that's great.

However, the other issue with incorrect results is still happening on `4c32238 - bump to 25`, and there are 3 issues that I can see.

The first is what i've already mentioned, the list is cut short even tho there are valid entries in the link.

<img width="988" height="356" alt="Image" src="https://github.com/user-attachments/assets/4d5f4380-85e0-4d63-b26c-59804762edf2" />

The second one is a bogus value being shown even tho the entry is valid. My `thing` struct (as shown in the first post) has a PrevChunk, and here's what happens when i view it:

<img width="969" height="517" alt="Image" src="https://github.com/user-attachments/assets/1895867f-f962-49ae-b88d-92257bd8f30f" />

The third issue is simpler to just show:

<img width="994" height="242" alt="Image" src="https://github.com/user-attachments/assets/4c6ff4c8-0863-4991-9288-bc137d82f926" />

The value at [4] can be reached by going `World.ChunkHashmap[3].NextHashmap.NextHashmap` so i can sortof understand why it's shown, but even then it's the wrong link and the wrong number of resulting entries.

This was all checked with all `rdi` files deleted before running the executable.

**Comment by Strewya** [comment]
I've debugged raddbg with remedybg to figure out what is happening, and i've found out that `list` requires you to pass in the first argument by value, not by pointer, and i've been passing in pointers this whole time. Oops. :)

While i'll admit this is somewhat of an error on my end not understanding this, i also couldn't have found this out without debugging the debugger. I think raddbg should either have a better tooltip explaining this or (ideally in my opinion) allow pointers in the `list` lens, but if that's not really feasible, the better tooltip will suffice.

Right now when hovering the `expression` label of the `list` popup, it says `An expression describing the first node in the list` - this makes me think that the expression should be a pointer, not a value, so maybe make this text more explicit in what the expression has to be. Also perhaps add it to the raddbg_readme.md :)
